baseURL = 'http://evilrouter.com/'
languageCode = 'en-us'
title = 'Evil Router'
theme = 'm10c'
[params]
  # Author
  author = "Bernard McCormack"
  # Description
  description = "Cloud Enthusiast and Linux Advocate"
[services]
  [services.googleAnalytics]
    ID = "G-BRMY7L3EZM"
